# Generated by Django 5.1.7 on 2026-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_full_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='planner_eve_user_id_b15153_idx',
            old_name='planner_eve_user_sc_del_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='planner_eve_user_id_588f1d_idx',
            old_name='planner_eve_user_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='planner_eve_start_a_557c27_idx',
            old_name='planner_eve_start_at_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='planner_pro_user_id_85d5b8_idx',
            old_name='planner_proj_user_sc_del_idx',
        ),
        migrations.AlterField(
            model_name='scope',
            name='code',
            field=models.CharField(choices=[('personal', 'Личное'), ('work', 'Рабочее')], max_length=20),
        ),
    ]
