# Generated by Django 5.1.7 on 2026-10-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_rename_planner_eve_user_sc_del_idx_planner_eve_user_id_b15153_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
