# Generated by Django 5.1.7 on 2026-08-05 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
