# Generated by Django 5.1.7 on 2026-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='insurance_reminder_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='plan_reminder_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='transport_tax_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='transport_tax_month',
            field=models.IntegerField(default=12),
        ),
    ]
