# Generated by Django 5.1.7 on 2026-10-01 02:53

import apps.api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to=apps.api.models.staged_upload_path)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(default='.bin', max_length=10)),
                ('size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_bot_upload',
                'ordering': ['-created_at'],
            },
        ),
    ]
