FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DJANGO_SETTINGS_MODULE=config.settings.prod

WORKDIR /app

# Добавляем аргумент с дефолтным значением для продакшена
ARG REQUIREMENTS_FILE=requirements/prod.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    gcc \
    libffi-dev \
    libjpeg62-turbo \
    libpng16-16 \
    libfreetype6 \
    fonts-noto-cjk \
    fontconfig \
    libglib2.0-0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libpangoft2-1.0-0 \
    libgdk-pixbuf-2.0-0 \
    fonts-dejavu-core \
    && fc-cache -f \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/ ./requirements/

RUN pip install --no-cache-dir -r ${REQUIREMENTS_FILE}

COPY . .

RUN python manage.py collectstatic --noinput

EXPOSE 8001

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8001", "--workers", "3"]
