# Generated by Django 5.1.7 on 2026-08-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_engine_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='receipt_photo',
            field=models.ImageField(blank=True, upload_to='vehicles/fuel/'),
        ),
    ]
