# Generated by Django 5.1.7 on 2026-08-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_fuelentry_notes_fuelentry_receipt_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='link_purchase',
            field=models.BooleanField(default=False, help_text='Показывать штраф в расходах (запись в покупках с категорией «Штрафы»)'),
        ),
    ]
