# Generated by Django 5.1.7 on 2026-08-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_fine_link_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedevent',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
