# Generated by Django 5.1.7 on 2026-09-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_plannedevent_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='renewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_policies', to='vehicles.insurance', verbose_name='Продлён полисом'),
        ),
    ]
