# Generated by Django 5.1.7 on 2026-09-30 07:21

import apps.vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_insurance_renewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicephoto',
            name='image',
            field=models.ImageField(upload_to=apps.vehicles.models.service_photo_path),
        ),
    ]
