# Generated by Django 5.1.7 on 2026-10-03 12:29

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_servicephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
