# Generated by Django 5.1.7 on 2026-10-01 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChatBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot', models.CharField(choices=[('vehicle', 'Бот Бортжурнала'), ('planner', 'Бот Записной книжки')], max_length=20)),
                ('chat_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_chat_binding',
                'constraints': [models.UniqueConstraint(fields=('user', 'bot'), name='uniq_user_bot_chat')],
            },
        ),
    ]
